import type {
  ConversationTurn,
  GroupContext,
  Plan,
  Reminder,
} from "./types";

export const fixturePlans: Plan[] = [
  {
    id: "plan_001",
    title: "Draft Q3 product roadmap",
    description:
      "Outline the three pillars for Q3: reliability, growth, AI features.",
    status: "draft",
    priority: "high",
    owner_id: "user_linh",
    owner_name: "Linh Tran",
    group_id: "group_product",
    start_at: "2026-05-01T09:00:00Z",
    due_at: "2026-05-15T17:00:00Z",
    recurrence: { kind: "none" },
    tags: ["roadmap", "q3"],
    created_at: "2026-04-18T08:00:00Z",
    updated_at: "2026-04-22T12:30:00Z",
  },
  {
    id: "plan_002",
    title: "Daily standup reminder",
    description: "Ping the team in the WeChat group at 9:15 every weekday.",
    status: "active",
    priority: "medium",
    owner_id: "user_zhen",
    owner_name: "Zhen Wu",
    group_id: "group_product",
    start_at: "2026-04-01T09:15:00Z",
    due_at: null,
    recurrence: { kind: "daily", time: "09:15" },
    tags: ["standup", "daily"],
    created_at: "2026-03-28T04:00:00Z",
    updated_at: "2026-04-20T09:15:00Z",
  },
  {
    id: "plan_003",
    title: "Weekly ops review",
    description: "Roll up metrics from Datadog; paste the deck into the group.",
    status: "active",
    priority: "medium",
    owner_id: "user_ming",
    owner_name: "Ming Chen",
    group_id: "group_ops",
    start_at: "2026-04-05T14:00:00Z",
    due_at: null,
    recurrence: { kind: "weekly", day_of_week: 1, time: "14:00" },
    tags: ["ops", "metrics"],
    created_at: "2026-03-20T02:00:00Z",
    updated_at: "2026-04-21T14:00:00Z",
  },
  {
    id: "plan_004",
    title: "Migrate billing to Stripe v2",
    description: "Finish the cutover before the May invoice run.",
    status: "completed",
    priority: "high",
    owner_id: "user_linh",
    owner_name: "Linh Tran",
    group_id: null,
    start_at: "2026-02-01T00:00:00Z",
    due_at: "2026-04-10T00:00:00Z",
    recurrence: { kind: "none" },
    tags: ["billing", "infra"],
    created_at: "2026-01-28T00:00:00Z",
    updated_at: "2026-04-09T23:15:00Z",
  },
  {
    id: "plan_005",
    title: "Investigate onboarding drop-off",
    description:
      "Paused while we wait for the revised analytics dashboard from data.",
    status: "paused",
    priority: "low",
    owner_id: "user_zhen",
    owner_name: "Zhen Wu",
    group_id: "group_product",
    start_at: "2026-04-15T00:00:00Z",
    due_at: "2026-06-01T00:00:00Z",
    recurrence: { kind: "none" },
    tags: ["growth", "analytics"],
    created_at: "2026-04-10T00:00:00Z",
    updated_at: "2026-04-17T15:00:00Z",
  },
  {
    id: "plan_006",
    title: "Monthly finance sync",
    description: "Close-of-month checklist and runway review.",
    status: "active",
    priority: "low",
    owner_id: "user_ming",
    owner_name: "Ming Chen",
    group_id: "group_ops",
    start_at: "2026-01-31T16:00:00Z",
    due_at: null,
    recurrence: { kind: "monthly", day_of_month: 28, time: "16:00" },
    tags: ["finance"],
    created_at: "2026-01-15T00:00:00Z",
    updated_at: "2026-03-28T16:00:00Z",
  },
];

export const fixtureReminders: Reminder[] = [
  {
    id: "rem_001",
    plan_id: "plan_002",
    fire_at: "2026-04-24T09:15:00Z",
    status: "scheduled",
    channel: "wechat",
    message: "Morning — standup in 15 minutes.",
    created_at: "2026-04-23T09:15:00Z",
    sent_at: null,
  },
  {
    id: "rem_002",
    plan_id: "plan_002",
    fire_at: "2026-04-23T09:15:00Z",
    status: "sent",
    channel: "wechat",
    message: "Morning — standup in 15 minutes.",
    created_at: "2026-04-22T09:15:00Z",
    sent_at: "2026-04-23T09:15:03Z",
  },
  {
    id: "rem_003",
    plan_id: "plan_002",
    fire_at: "2026-04-22T09:15:00Z",
    status: "sent",
    channel: "wechat",
    message: "Morning — standup in 15 minutes.",
    created_at: "2026-04-21T09:15:00Z",
    sent_at: "2026-04-22T09:15:02Z",
  },
  {
    id: "rem_004",
    plan_id: "plan_001",
    fire_at: "2026-05-10T14:00:00Z",
    status: "scheduled",
    channel: "email",
    message: "Roadmap draft review — one week out.",
    created_at: "2026-04-20T00:00:00Z",
    sent_at: null,
  },
  {
    id: "rem_005",
    plan_id: "plan_003",
    fire_at: "2026-04-28T14:00:00Z",
    status: "scheduled",
    channel: "wechat",
    message: "Ops review — paste metrics deck.",
    created_at: "2026-04-22T00:00:00Z",
    sent_at: null,
  },
];

export const fixtureGroups: GroupContext[] = [
  {
    id: "group_product",
    name: "Product · Core",
    platform: "wechat",
    external_id: "wx_product_core_2024",
    last_seen_at: "2026-04-23T08:44:00Z",
    member_count: 8,
    active_plan_count: 3,
    members: [
      { id: "user_linh", display_name: "Linh Tran", role: "admin" },
      { id: "user_zhen", display_name: "Zhen Wu", role: "member" },
      { id: "user_ming", display_name: "Ming Chen", role: "member" },
    ],
  },
  {
    id: "group_ops",
    name: "Ops & Finance",
    platform: "wechat",
    external_id: "wx_ops_finance",
    last_seen_at: "2026-04-22T18:10:00Z",
    member_count: 5,
    active_plan_count: 2,
    members: [
      { id: "user_ming", display_name: "Ming Chen", role: "admin" },
      { id: "user_sara", display_name: "Sara Park", role: "member" },
    ],
  },
];

export const fixtureConversations: Record<string, ConversationTurn[]> = {
  group_product: [
    {
      id: "turn_001",
      group_id: "group_product",
      role: "user",
      sender_name: "Linh Tran",
      content: "Can you remind us about the standup tomorrow?",
      tool_calls: [],
      tool_call_id: null,
      created_at: "2026-04-22T22:01:00Z",
    },
    {
      id: "turn_002",
      group_id: "group_product",
      role: "assistant",
      sender_name: null,
      content: "Sure, scheduling a 09:00 reminder for the group.",
      tool_calls: [
        {
          id: "call_001",
          name: "create_reminder",
          arguments: {
            plan_id: "plan_002",
            fire_at: "2026-04-23T09:00:00Z",
            channel: "wechat",
          },
        },
      ],
      tool_call_id: null,
      created_at: "2026-04-22T22:01:12Z",
    },
    {
      id: "turn_003",
      group_id: "group_product",
      role: "tool",
      sender_name: "create_reminder",
      content: '{"ok": true, "reminder_id": "rem_001"}',
      tool_calls: [],
      tool_call_id: "call_001",
      created_at: "2026-04-22T22:01:13Z",
    },
    {
      id: "turn_004",
      group_id: "group_product",
      role: "assistant",
      sender_name: null,
      content: "Done — I will ping the group at 09:00 tomorrow.",
      tool_calls: [],
      tool_call_id: null,
      created_at: "2026-04-22T22:01:14Z",
    },
    {
      id: "turn_005",
      group_id: "group_product",
      role: "user",
      sender_name: "Zhen Wu",
      content: "Also: what is outstanding for the Q3 roadmap?",
      tool_calls: [],
      tool_call_id: null,
      created_at: "2026-04-23T03:12:00Z",
    },
    {
      id: "turn_006",
      group_id: "group_product",
      role: "assistant",
      sender_name: null,
      content: "Pulling up the active plan list now.",
      tool_calls: [
        {
          id: "call_002",
          name: "list_plans",
          arguments: { group_id: "group_product", status: "active" },
        },
      ],
      tool_call_id: null,
      created_at: "2026-04-23T03:12:04Z",
    },
    {
      id: "turn_007",
      group_id: "group_product",
      role: "tool",
      sender_name: "list_plans",
      content: '{"count": 2, "plan_ids": ["plan_002", "plan_003"]}',
      tool_calls: [],
      tool_call_id: "call_002",
      created_at: "2026-04-23T03:12:05Z",
    },
    {
      id: "turn_008",
      group_id: "group_product",
      role: "assistant",
      sender_name: null,
      content:
        "Two active plans: daily standup reminder, and the weekly ops review. Roadmap draft is still in Draft — Linh owns it.",
      tool_calls: [],
      tool_call_id: null,
      created_at: "2026-04-23T03:12:07Z",
    },
    {
      id: "turn_009",
      group_id: "group_product",
      role: "user",
      sender_name: "Linh Tran",
      content: "Thanks — I will move it to Active after lunch.",
      tool_calls: [],
      tool_call_id: null,
      created_at: "2026-04-23T03:13:00Z",
    },
    {
      id: "turn_010",
      group_id: "group_product",
      role: "assistant",
      sender_name: null,
      content: "Noted. Ping me when you want a status change.",
      tool_calls: [],
      tool_call_id: null,
      created_at: "2026-04-23T03:13:06Z",
    },
  ],
  group_ops: [
    {
      id: "turn_101",
      group_id: "group_ops",
      role: "user",
      sender_name: "Ming Chen",
      content: "Kick off this week's ops review.",
      tool_calls: [],
      tool_call_id: null,
      created_at: "2026-04-21T05:58:00Z",
    },
    {
      id: "turn_102",
      group_id: "group_ops",
      role: "assistant",
      sender_name: null,
      content: "On it — pulling the dashboard snapshot.",
      tool_calls: [
        {
          id: "call_101",
          name: "fetch_metrics",
          arguments: { range: "last_7_days" },
        },
      ],
      tool_call_id: null,
      created_at: "2026-04-21T05:58:03Z",
    },
  ],
};
