"""0003_bot_sessions

Revision ID: 51e427f104f4
Revises: 0002_group_last_context_token
Create Date: 2026-04-23 11:37:53.546515

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003_bot_sessions'
down_revision: str | None = '0002_group_last_context_token'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('wechat_user_id', sa.String(length=128), nullable=True),
    sa.Column('bot_user_id', sa.String(length=128), nullable=True),
    sa.Column('bot_token', sa.String(length=512), nullable=False),
    sa.Column('baseurl', sa.String(length=256), nullable=True),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('last_inbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_outbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_wakeup_ping_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_context_token', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group_contexts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('bot_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bot_sessions_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_sessions_wechat_user_id'), ['wechat_user_id'], unique=True)

    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.alter_column('wechat_user_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.alter_column('wechat_user_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    with op.batch_alter_table('bot_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_sessions_wechat_user_id'))
        batch_op.drop_index(batch_op.f('ix_bot_sessions_group_id'))

    op.drop_table('bot_sessions')
    # ### end Alembic commands ###
